In [16]:
import requests
import pandas as pd

In [27]:
#Use your own API key to launch the request.
response1= requests.get('https://api.census.gov/data/timeseries/poverty/saipe?get=SAEMHI_PT,SAEPOVRTALL_PT,NAME&for=state:*&time=2020&key=YOUR_KEY')
print(response1)

<Response [200]>

In [49]:
json1=response1.json()
json1
df1=pd.DataFrame(json1[1:])
df1.columns=json1[0]
df1

   SAEMHI_PT SAEPOVRTALL_PT                  NAME  time state
0      53958           14.9               Alabama  2020    01
1      79961            9.6                Alaska  2020    02
2      64652           12.8               Arizona  2020    04
3      51146           15.2              Arkansas  2020    05
4      83001           11.5            California  2020    06
5      77688            9.0              Colorado  2020    08
6      79723            9.7           Connecticut  2020    09
7      71335           10.9              Delaware  2020    10
8      91957           15.0  District of Columbia  2020    11
9      61724           12.4               Florida  2020    12
10     62800           14.0               Georgia  2020    13
11     86878            8.9                Hawaii  2020    15
12     62603           10.1                 Idaho  2020    16
13     71243           11.0              Illinois  2020    17
14     60794           11.6               Indiana  2020    18
15     62362           10.2                  Iowa  2020    19
16     63214           10.6                Kansas  2020    20
17     54074           14.9              Kentucky  2020    21
18     51730           17.8             Louisiana  2020    22
19     59145           10.6                 Maine  2020    23
20     88589            9.0              Maryland  2020    24
21     87288            9.4         Massachusetts  2020    25
22     61352           12.6              Michigan  2020    26
23     75489            8.3             Minnesota  2020    27
24     47368           18.7           Mississippi  2020    28
25     58812           12.1              Missouri  2020    29
26     57730           12.4               Montana  2020    30
27     64735            9.2              Nebraska  2020    31
28     64608           12.5                Nevada  2020    32
29     81415            7.0         New Hampshire  2020    33
30     87095            9.4            New Jersey  2020    34
31     52285           16.8            New Mexico  2020    35
32     73354           12.7              New York  2020    36
33     59616           12.9        North Carolina  2020    37
34     64289           10.2          North Dakota  2020    38
35     60360           12.6                  Ohio  2020    39
36     54512           14.3              Oklahoma  2020    40
37     67832           11.0                Oregon  2020    41
38     64898           10.9          Pennsylvania  2020    42
39     73919           10.6          Rhode Island  2020    44
40     57216           13.8        South Carolina  2020    45
41     61149           11.6          South Dakota  2020    46
42     56962           13.6             Tennessee  2020    47
43     66048           13.4                 Texas  2020    48
44     77785            7.3                  Utah  2020    49
45     67717            9.4               Vermont  2020    50
46     79154            9.2              Virginia  2020    51
47     80319            9.5            Washington  2020    53
48     49202           15.8         West Virginia  2020    54
49     64901           10.0             Wisconsin  2020    55
50     67284            9.2               Wyoming  2020    56

In [57]:
response2=requests.get('https://api.census.gov/data/2020/dec/pl?get=P4_001N,P4_002N,P4_005N,P4_006N,P4_007N,P4_008N,P4_009N,P4_010N,P4_011N,NAME&for=state:*&key=YOUR_KEY')
json2=response2.json()
df2=pd.DataFrame(json2[1:])
df2.columns=json2[0]
df2.drop(columns='state')
df2

,P4_001N,P4_002N,P4_005N,P4_006N,P4_007N,P4_008N,P4_009N,P4_010N,P4_011N,NAME,state
0,10353548,704258,7884010,1039831,12123,398348,2519,36798,275661,Pennsylvania,42
1,30827105,11083294,11672897,1694380,122657,4906293,109178,162339,1076067,California,06
2,1432932,23483,1293040,52002,2761,12233,333,2981,46099,West Virginia,54
3,2324051,316610,1798000,25370,20985,62825,23424,8588,68249,Utah,49
4,16088135,2925886,8761517,2176551,42624,1551634,4766,137513,487644,New York,36
5,575161,60375,234767,223540,1063,30795,305,2876,21440,District of Columbia,11
6,554003,33441,340580,16566,75017,34290,8122,3308,42679,Alaska,02
7,17339232,4332685,9476700,2344909,34541,510811,9027,96170,534389,Florida,12
8,4014460,231124,2603975,964667,13333,70272,2212,12598,116279,South Carolina,45
9,596093,21603,503153,17608,24119,10252,643,1284,17431,North Dakota,38
10,1110085,17656,1017504,16551,5603,13336,332,3365,35738,Maine,23
11,8220274,742918,4342333,2462933,16155,367605,4556,37161,246613,Georgia,13
12,3917166,166856,2564544,976732,18137,59997,1872,9084,119944,Alabama,01
13,1120680,39800,995751,13858,1930,27989,303,4443,36606,New Hampshire,33
14,3370652,389394,2526275,60012,32769,156707,13091,17541,174863,Oregon,41
15,441337,38153,370041,3666,7883,4139,355,1760,15340,Wyoming,56
16,5541976,1489617,3218094,236894,189473,199796,10590,23269,174243,Arizona,04
17,3570548,223662,2082110,1066511,19531,67983,1322,11524,97905,Louisiana,22
18,5192579,350929,4065650,462446,10490,124975,1961,15652,160476,Indiana,18
19,1376400,151700,1121466,9946,13935,21008,2442,5927,49976,Idaho,16
20,2869227,430695,1913793,279080,4967,132859,757,19450,87626,Connecticut,09
21,1155905,93107,275624,18059,2000,458268,105218,4224,199405,Hawaii,15
22,9999469,1620312,6123548,1356415,13313,596814,2354,31674,255039,Illinois,17
23,5663723,621508,3988985,351465,7430,407742,1391,68601,216601,Massachusetts,25
24,21866700,7907319,9437993,2575257,67248,1205578,20144,77691,575470,Texas,48
25,850123,29908,727553,3781,42717,6666,642,3326,35530,Montana,30
26,1476127,145297,1169255,66088,10112,38794,942,4314,41325,Nebraska,31
27,9207562,336028,7218892,1073902,15496,228920,3233,28843,302248,Ohio,39
28,4509576,864196,3095664,168127,26942,155965,6646,21838,170198,Colorado,08
29,7281310,1435999,3966396,896947,8209,740609,1586,48057,183507,New Jersey,34
30,4815202,492262,2401360,1388741,9788,332666,2035,23196,165154,Maryland,24
31,6745054,614314,4136979,1224840,15376,478337,4754,29385,241069,Virginia,51
32,524482,11113,474146,6143,1632,9117,144,1929,20258,Vermont,50
33,8155099,724311,5189633,1620569,77335,257602,5144,30113,250392,North Carolina,37
34,2312273,162002,1653772,331235,15691,39675,8250,5260,96388,Arkansas,05
35,6024689,690674,4058504,223861,68149,584457,43639,31957,323448,Washington,53
36,2229316,241586,1683982,122508,16995,65780,2173,6978,89314,Kansas,20
37,3010698,295621,1963854,212976,219638,69282,5082,10012,234233,Oklahoma,40
38,4612300,284069,3774226,258704,35459,126019,1446,12562,119815,Wisconsin,55
39,2277599,68637,1315451,799388,9701,25718,767,4638,53299,Mississippi,28
40,4775612,197173,3723642,514169,18642,104558,6340,14896,196192,Missouri,29
41,7914602,367645,5928796,1021516,36450,258756,1985,25724,273730,Michigan,26
42,887594,125988,642435,41924,2699,31412,255,8453,34428,Rhode Island,44
43,4389033,218767,3509053,257353,39560,214681,1861,14680,133078,Minnesota,27
44,2450103,134104,2093769,86796,6662,56772,3447,5779,62774,Iowa,19
45,1638989,726764,664062,30778,137360,28989,1199,7925,41912,New Mexico,35
46,2413326,609396,1205651,219333,18317,224400,17118,12441,106670,Nevada,32
47,783543,67906,489226,161576,2090,33202,240,3024,26279,Delaware,10
48,2724903,2692743,21575,3785,276,2392,69,2089,1974,Puerto Rico,72
49,3483900,133075,2905545,265961,6657,54971,2391,8970,106330,Kentucky,21
50,669255,23855,556081,11408,47084,9918,395,1472,19042,South Dakota,46
51,5384473,305717,3958296,812207,12745,103925,2625,15557,173401,Tennessee,47

In [44]:
response3=requests.get('https://api.census.gov/data/timeseries/eits/qtax?get=data_type_code,time_slot_id,seasonally_adj,category_code,cell_value,error_data&for=state:*&time=2012&key=YOUR_KEY')
print(response3)

<Response [400]>